# Site settings
title: software[F5]
email: 
description: Opinionated views on agentic AI and software engineering.
baseurl: ""
url: "https://softwaref5.github.io"
linkedin_username: 
github_username:  
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

include:
 - _pages 

collections:
  somefolder:
    output: true
